name: ac_tools_py3_7_base_TESTv2
channels:
    - defaults
dependencies:
    - python=3.7
    - cartopy
    - matplotlib
    - netcdf4
    - numpy
    - pandas
    - pytest
    - scipy
    - pyyaml
    - xarray
